# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 765c76e77a706e7324e4d85ecfc946d7706f5036616f1113e90e7bed98ce99cb5a8d5294655b6eac48e0d67e92e052b524f359abbc35200061527413522f5730

test:
  secret_key_base: 55e4e45d2d753984bc064db4e1ca88df3ae21943f8a53f80572ceba68a2015573db13bdad519e6f9817abef55f1064ed77a28d2aa90de5f9ad1b143bd401ffd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
